FROM golang:latest AS builder

WORKDIR /app

RUN go mod init hello
COPY src/* .


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hello .

#otimizando a imagem
FROM scratch

COPY --from=builder /app/hello /hello

CMD ["/hello"]